try 2

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -59,10 +59,10 @@ jobs:
         { output=$(./build.py --target $(target) 2>&1 1>&3-) ;} 3>&1
         final_status=$(<status.txt)
         echo "FINAL STATUS  = ${final_status}"
-        echo "POSSIBLE ERRORS: ${output}"
+        #echo "POSSIBLE ERRORS: ${output}"
         
         if [ $final_status != "0" ]; then
-          echo "Build & Testing Failed! \n ${output}" >&2
+          #echo "Build & Testing Failed! \n ${output}" >&2
           output=$(echo "$output" | sed ':a;N;$!ba;s/\n/%0D%0A/g')
           echo "##vso[task.setvariable variable=errors]${output}"
         fi
@@ -74,6 +74,9 @@ jobs:
       targetType: 'inline'
       script: |
         rm -rf status.txt
+        while read p; do
+          echo "$p"
+        done < $(errors)
         echo $(errors)
   
   
