Checking errors with new line

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -60,9 +60,10 @@ jobs:
         final_status=$(<status.txt)
         echo "FINAL STATUS  = ${final_status}"
         echo "POSSIBLE ERRORS: ${output}"
-
+        output=$(echo "${output}" | sed ':a;N;$!ba;s/\n/%0D%0A/g')
         if [ $final_status != "0" ]; then
-          echo "##vso[task.setvariable variable=errors]${output}" >&2
+          echo "Build & Testing Failed! \n ${output}" >&2
+          echo "##vso[task.setvariable variable=errors]${output}"
         fi
       failOnStderr: true
   - task: Bash@3
