removing display errors

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,3 @@
-variables:
-  - name: 'errors'
-    value: null
 # Pipeline will be triggered for PR & any updates on the PR on all branches
 pr:
   autoCancel: true
@@ -59,24 +56,18 @@ jobs:
         { output=$(./build.py --target $(target) 2>&1 1>&3-) ;} 3>&1
         final_status=$(<status.txt)
         echo "FINAL STATUS  = ${final_status}"
-        #echo "POSSIBLE ERRORS: ${output}"
+        echo "POSSIBLE ERRORS: ${output}"
         
         if [ $final_status != "0" ]; then
-          #echo "Build & Testing Failed! \n ${output}" >&2
-          output=$(echo "$output" | sed ':a;N;$!ba;s/\n/%0D%0A/g')
-          echo "##vso[task.setvariable variable=errors]${output}"
+          echo "Build & Testing Failed! \n ${output}" >&2
         fi
       failOnStderr: true
   - task: Bash@3
     condition: always()
-    displayName: Display Build & Test Errors
+    displayName: Cleanup
     inputs:
       targetType: 'inline'
       script: |
         rm -rf status.txt
-        while read p; do
-          echo "$p"
-        done < $(errors)
-        echo $(errors)
   
   
